bug:
  - '(bug|issue)'
  
documentation:
  - '(documentation|wiki)'
  
duplicate:
  - '(duplicate|duplicate issue)'
  
enhancement:
  - '(enhancement|feature|custom)'
  
good first issue:
  - '(good first issue|easy)'
  
help wanted:
  - '(help wanted|help wanted!)'
  
invalid:
  - '(invalid|bug)'
  
question:
  - '(question|question!)'
  
wontfix:
  - '(wontfix|wontfix!)'
