# .github/issue-labeler.yml

issues:
  - label: "bug"
    title: ["bug", "error", "issue"]
  - label: "enhancement"
    title: ["feature", "enhancement", "improvement"]
  - label: "question"
    title: ["question", "help"]
  - label: "documentation"
    title: ["docs", "documentation"]
