var SHEET_DATA = JSON.parse($('#sheet-data').text()); // * Get the data from the sheet
var QUESTION_ELEMENT = $('quiz-question-text').get(0);
var ANSWER_ELEMENTS: any[] = [$('quiz-answer')];
var QUIZ_SCORE_ELEMENT = $('quiz-score').get(0);
var QUIZ_STATUS_ELEMENT = $('quiz-status').get(0);
var QUIZ_HINT_TOGGLE = $('quiz-hint-toggle').get(0);
var QUIZ_HINT_TEXT = $('quiz-hint-text').get(0);
var MAIN = $('main').get(0);
var QUIZ_FINISH_TEXT = $('#quiz-finish');
var QUIZ_FINISH = $('quiz-finish').get(0);
var QUIZ_START = $('quiz-start').get(0);
var AUDIO_CORRECT = $('#correct_Audio').get(0);
var AUDIO_INCORRECT = $('#incorrect_Audio').get(0);
var AUDIO_TOGGLE = $('quiz-audio-toggle').get(0);
