# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: 'Labeler: Issues and Pull Requests'
on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - closed
    
  issues:
    types:
      - opened
      - reopened
      - edited
      - closed


jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/pulls-labeler.yml
    - uses: github/issue-labeler@v2.5 #May not be the latest version
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/issues-labeler.yml
        not-before: 2020-01-15T02:54:32Z
        enable-versioned-regex: 0
