# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Wiki Sync
        # You may pin to the exact commit or the version.
        # uses: JoeIzzard/ghaction-wiki-sync@56fa2d2877578ffd8480f8694eff93de0fac5d4f
        uses: JoeIzzard/ghaction-wiki-sync@v1
        with:
          # The username of the repo owner
          username: HoleInOneStudios
          # The access token with Repo access. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
          access_token: ${{ secrets.ACTION_TOKEN }}
          # The folder you want to sync the repo with
          wiki_folder: docs # optional, default is wiki
          # A custom commit message to be used
          commit_message: # optional, default is action: wiki sync
          # The email address to use with the commit
          commit_username: 'github-actions[bot]'
          # The email address to use when committing
          commit_email: 'github-actions[bot]@users.noreply.github.com'
