on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
name: Wiki Sync
jobs:
    update-wiki:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Sync Wiki
            uses: joeizzard/action-wiki-sync@master
            with:
                username: HoleInOneStudios
                access_token: ${{ secrets.GITHUB_TOKEN }}
                wiki_folder: docs
                commit_username: 'Wiki Sync Action'
                commit_email: 'commit@holeinonestudios.org'
                commit_message: 'action: wiki sync'
